apiVersion: v1
kind: Service
metadata:
  name: gitlab-service
  labels:
    app: gitlab
    stage: dev
spec:
  ports:
  - name: http
    port: 80
  - name: https
    port: 443 
  selector:
    type: gitlab 
