kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nextcloud 
  labels:
    app: nextcloud 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: nextcloud 
  template:
    metadata:
      labels:
        app: nextcloud 
        version: v1.0
    spec:
      containers:
      - name: nextcloud 
        image: harbor.pks-reg.lab/library/nextcloud:latest 
        ports:
        - containerPort: 80
